
ALTER PROC USP_HOSPITALIZACION
(
	@IDPACIENTE         INT,
	@IDHABITACION       INT,
	@MOTIVO             VARCHAR(2000),
	@ADMINISTRATIVO     INT,
	@MEDICO             INT,
	@IDHOSPITALIZACION  INT OUT,
	@ESTADO             INT OUT
)
AS
BEGIN
	DECLARE @CONT INT;
	SET @ESTADO = 0; -- Valor por defecto
	BEGIN TRY 
		-- Paso 1: Inicio de Tx
		BEGIN TRANSACTION; 
		-- Paso 2: Verificar existencia de habitación
		SELECT @CONT = COUNT(1)
		FROM dbo.HABITACION WHERE IDHABITACION = @IDHABITACION;
		IF(@CONT=0)
		BEGIN
			SET @ESTADO = 2;
			THROW 51000, 'Habitación no existe.', 1;
		END;
		-- Paso 3: Verificar disponibilidad de habitación
		SELECT @CONT = COUNT(1)
		FROM dbo.HABITACION 
		WHERE IDHABITACION = @IDHABITACION AND DISPONIBLE=1;
		IF(@CONT=0)
		BEGIN
			SET @ESTADO = 3;
			THROW 51000, 'Habitación no disponible.', 1;
		END;

		-- Paso : Registrar hospitalización
		INSERT INTO DBO.HOSPITALIZACION(IDPACIENTE,IDHABITACION,FECHA_INGRESO,
		MOTIVO,ADMINISTRATIVO,MEDICO) VALUES(@IDPACIENTE,@IDHABITACION,GETDATE(),
		'Dolores intensos de estomago.',@ADMINISTRATIVO,@MEDICO);
		SELECT @IDHOSPITALIZACION = @@IDENTITY;
		-- PAso : Cambiar estado de habitacion
		UPDATE dbo.HABITACION
		SET DISPONIBLE=0
		WHERE IDHABITACION = @IDHABITACION;
		-- Paso : Fin de Tx
		COMMIT TRANSACTION; 
	END TRY 
	BEGIN CATCH 
		IF(@ESTADO=0) SET @ESTADO=1;
		-- Cancela la Tx
		ROLLBACK TRANSACTION;
		THROW;
	END CATCH;
END;
GO


insert into PACIENTE values('AAA','ab@abc.com','BBB');
select @@Identity;
go

select * from dbo.PACIENTE;
go

SELECT * FROM DBO.HABITACION WHERE IDHABITACION = 8;

DECLARE @IDHOSPITALIZACION INT, @ESTADO INT;
EXEC USP_HOSPITALIZACION 3,8,
	'Dolor intenso de estomago',3,8,
	@IDHOSPITALIZACION OUT, @ESTADO OUT
PRINT 'ID: ' + CAST(@IDHOSPITALIZACION AS VARCHAR(20));
PRINT 'ESTADO: ' + CAST(@ESTADO AS VARCHAR(20));
GO

SELECT * FROM DBO.HOSPITALIZACION WHERE IDHOSPITALIZACION=1;